import { type ReactNode } from 'react';

// Severity of a toast. Modeled as an E-prefixed const-object enum (enums as a
// language feature are banned). The kebab-case values mirror EBannerKind exactly,
// so a toast maps onto the shared Banner surface and its severity->role mapping
// without re-deriving it; info/success/warning announce politely (role="status")
// and danger announces assertively (role="alert"). A shared ESeverity is
// deliberately NOT hoisted here, since that would touch the shipped Banner.
export const EToastKind: {
    readonly Info: 'info';
    readonly Success: 'success';
    readonly Warning: 'warning';
    readonly Danger: 'danger';
} = {
    Info: 'info',
    Success: 'success',
    Warning: 'warning',
    Danger: 'danger',
};
export type EToastKind = (typeof EToastKind)[keyof typeof EToastKind];

// Corner the toast viewport anchors to. The kebab-case values double as the
// data-placement attribute the CSS keys off to pin the fixed viewport and choose
// the stacking direction. Defaults to BottomRight.
export const EToastPlacement: {
    readonly TopRight: 'top-right';
    readonly TopLeft: 'top-left';
    readonly BottomRight: 'bottom-right';
    readonly BottomLeft: 'bottom-left';
} = {
    TopRight: 'top-right',
    TopLeft: 'top-left',
    BottomRight: 'bottom-right',
    BottomLeft: 'bottom-left',
};
export type EToastPlacement =
    (typeof EToastPlacement)[keyof typeof EToastPlacement];

// One queued toast. `id` is generated by the provider (notify returns it). `kind`
// drives the severity surface and live-region role. `message` is the body and
// `title` the optional heading. `durationMs` overrides the provider default;
// a value <= 0 makes the toast sticky (no auto-dismiss). `tone` flows through the
// shared tone scope; `icon` is an optional decorative leading slot (aria-hidden).
export type ToastRecord = Readonly<{
    id: string;
    kind: EToastKind;
    message: ReactNode;
    title?: ReactNode;
    durationMs?: number;
    tone?: string;
    icon?: ReactNode;
}>;

// The notify input is a toast record without its id; the provider generates the
// id and returns it from notify.
export type ToastInput = Omit<ToastRecord, 'id'>;

// The imperative sink exposed by useToast. `notify` enqueues a toast and returns
// the generated id; `dismiss` removes one by id; `clear` empties the queue.
export type ToastContextValue = Readonly<{
    notify: (input: ToastInput) => string;
    dismiss: (id: string) => void;
    clear: () => void;
}>;

// Props for the ToastProvider. `placement` pins the viewport corner (default
// BottomRight). `defaultDurationMs` is the auto-dismiss delay for toasts that do
// not set their own (default 6000). `max` bounds the visible stack, dropping the
// oldest toasts beyond it (default 4; <= 0 means unbounded).
export type ToastProviderProps = Readonly<{
    children: ReactNode;
    placement?: EToastPlacement;
    defaultDurationMs?: number;
    max?: number;
}>;
